# Generated by Django 4.0.4 on 2022-06-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
